# force to go for VM container : it has more RAM, necessary for Xtend compilation and update site compression steps
# sudo : required

install: true

language: java

before_script:
 - echo $JAVA_OPTS
 - export JAVA_OPTS='-Xms1g -Xmx3g'
 - echo "MAVEN_OPTS='-Xmx3g'" > ~/.mavenrc

script : 
 - cd net.sourceforge.metrics.parent && mvn -e generate-sources install && cd - 
 - du -sh net.sourceforge.metrics.updatesite/target/repository

env:
  global:
    - MAVEN_OPTS="-Xmx3g"

cache:
  directories:
    - '$HOME/.m2/repository'

  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: net.sourceforge.metrics.updatesite/target/repository
  on:
    branch: master
